version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "106"
    network_mode: 'host'
    volumes:
      - /home/beraed/jellyfin/config:/config
      - /home/beraed/jellyfin/cache:/cache
      - /home/beraed/jellyfin/media:/media
    restart: 'unless-stopped'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
