version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    environment:
      FB_CONFIG: "/filebrowser.json"
      FB_DATABASE: "/database/filebrowser.db"
    volumes:
      - /home/beraed/filebrowser/filebrowser.json:/filebrowser.json
      - /home/beraed/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt/merged/cloud:/srv
    ports:
      - 8082:80
    restart: unless-stopped